### ISSUE TITLE
What does the keys of the collection schema mean?

### ISSUE THREAD

**Issue by mathieu-fontaine** [jamalex/notion-py#1]
I'm trying to understand the roles of the keys in the collection schema:
```json
"OBcJ": {"name": "Where to?", "type": "url"},
"dV$q": {"name": "Files", "type": "file"},
"title": {"name": "Name", "type": "title"}
```
i've tried my best to decipher those characters, but i'm out of ideas!

**Comment by jamalex** [comment]
They're just random identifiers. They're used to cross-reference between the schema and the property values on the row objects themselves. If you're creating a schema, you can just make them up. If you're using an existing schema, you don't need to think about them at all, as I made a slug-based attribute lookup system on CollectionRowBlock that lets you get and set values based on a slug of the property name.
