### ISSUE TITLE
Is there way get Notion table data , and then build chart Dashboard ? 

### ISSUE THREAD

**Issue by steveyang331** [jamalex/notion-py#134]
Is there way get Notion table data , and then build chart Dashboard ? 
and the chart use ChartJS or others, deploy on Github or observablehq.com, final embed Notion page. 

Thanks.

**Comment by pbajaria** [comment]
https://www.producthunt.com/posts/notion-charts-2

**Comment by steveyang331** [comment]
I know that solution. but it's not fit for me . 

> use ChartJS or others, deploy on Github or observablehq.com

But nevermind .
