### ISSUE TITLE
Dashes Broken in Markdown Links

### ISSUE THREAD

**Issue by cgamio** [jamalex/notion-py#155]
It looks like there was some change to how dashes are interpreted when setting block titles using Markdown.

My use case involves inserting links into documents by setting block titles to text that includes markdown defined links like `[dictionary](https://www.merriam-webster.com/)`. This breaks with newer versions of the library, I'm assuming due to changes related to #31. The above mentioned example tries to resolve `https://www.merriam⸻webster.com/` which doesn't work. It seems like all dashes in URL's in this case get replaced with `⸻` and don't get put back.

**Comment by jamalex** [comment]
Merged in via your PR #158. Will be released soon. Thanks!
