### ISSUE TITLE
How to obtain the token v2?

### ISSUE THREAD

**Issue by AnishDe12020** [jamalex/notion-py#172]
Can anyone tell me how I can obtain the token - v2.

**Comment by TheSpeedM** [comment]
From the README:
```python
# Obtain the `token_v2` value by inspecting your browser cookies on a logged-in session on Notion.so
```
----
In Firefox: (I don't have chrome to test this on but it should be similar)
1. Press `F12` in your webbrowser while being on Notion.so
2. In the menu, go to the storage tab
3. In this tab, go to cookies > notion.so
4. With notion.so selected it should be there named `token_v2` with the value right next to it

The value of `token_v2` is the value you should give to `NotionClient()` as the first argument

**Comment by fatemonk** [comment]
@TheSpeedM How long is this token lasts? Do I have to change it every now and then?

**Comment by TheSpeedM** [comment]
Next to the token in the `F12`-menu it says `Expires / Max-Age`. It looks like this is always set to far in the future, so it is basically endless.

**Comment by jamalex** [comment]
If you log out of your session in the browser, I think it resets. Otherwise it seems to last pretty indefinitely. But not guaranteed to.
