### ISSUE TITLE
IndexError when initializing NotionClient

### ISSUE THREAD

**Issue by jeetmehta** [jamalex/notion-py#180]
Thanks for building this - it's very valuable. For certain token_v2's, I'm noticing the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeetmehta/.local/share/virtualenvs/api-_eHp7W9M/lib/python3.8/site-packages/notion/client.py", line 68, in __init__
    self._update_user_info()
  File "/Users/jeetmehta/.local/share/virtualenvs/api-_eHp7W9M/lib/python3.8/site-packages/notion/client.py", line 77, in _update_user_info
    self.current_space = self.get_space(list(records["space"].keys())[0])
IndexError: list index out of range
```

when all I'm doing in the terminal is: 
```
client = NotionClient(token_v2='my_token')
```

Please advise!

**Comment by jeetmehta** [comment]
Looking into the module's code - it seems like for certain accounts, the `space` variable `{}`. Not sure why that's happening though

**Comment by jeetmehta** [comment]
One of the accounts that's facing this issue is a **shared space** - does the client fail in that case?

**Comment by raphodn** [comment]
I'm facing the exact same issue.
It used to work fine but I changed plan since, and I was using the `token_v2` of a member who has since become a guest, so it's probably the reason.
I fixed it by using the `token_v2` of the member (Personal Pro plan)

**Comment by jamalex** [comment]
Is there another place we could pull the space ID from for these accounts? (don't have such an account myself, so I can't test)
