### ISSUE TITLE
is it possible to change image size on any notion page?

### ISSUE THREAD

**Issue by mals14** [jamalex/notion-py#182]
I would like all by embedded image to show smaller in size like one can do manually by dragging the image corner.
Is it possible to do so using notion-py?
Or any other script?

Thank you.

**Comment by Arsenal591** [comment]
You can always download the image and resize it.
Also, there is a `width` query parameter when accesing the URL of image. Change it to a lower value and the resized version should be returned.

**Comment by mals14** [comment]
Got it. And I will look into both of those options.

But is it possible to somehow show the images smaller by default in the Notion browser / desktop app interface?
Ideally I would like to show every image that is attached on a page to show up as, say, only 400 pixel wide or 400 pixel tall by default.

That way when I attach images to a page, I do not have a page where text is so sparse because many images are showing on the page.

And would like to do so programmatically - dragging the corner is the manual way of doing it of course.

**Comment by Arsenal591** [comment]
You could set `width` attribute on any `ImageBlock` instance.

**Comment by mals14** [comment]
Thank you. That sounds great. I will be sure to use it and thank you very much for replying!
