### ISSUE TITLE
Image source always returns none

### ISSUE THREAD

**Issue by aivantg** [jamalex/notion-py#184]
For some reason, whenever I try to get an image block's source URL, it turns up none, even though it has worked in the past. 

The code I've been using to test looks something like this: 
```
for block in page.children: 
    if block.type == 'image': 
        print(block.source)
```

This will print "None" for all image blocks. I've tried accessing different properties like "display_source" and nothing works. 

Are other people having this issue?

**Comment by ruucm** [comment]
Same here. I think there are changes from Notion.

**Comment by ruucm** [comment]
Anyone knows how can I access each block's id on def "add_signed_prefix_as_needed"?

source URL should have block's id as a parameter from now

**Comment by velezhanski** [comment]
Same here, bump

**Comment by velezhanski** [comment]
Unfortunately I don't think this library is being maintained anymore. The last commit was made in January.

**Comment by ruucm** [comment]
#185 I request a quick pull request to resolve this issue. I'm quite a newbie on python, so I appreciate any improvements in my codes.

**Comment by velezhanski** [comment]
@ruucm Respect!
All works perfectly
