### ISSUE TITLE
NotionDate 'str' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by davinerd** [jamalex/notion-py#199]
`NotionDate` does not perform `_format_datetime` properly when passing a string.

Affected line: https://github.com/jamalex/notion-py/blob/master/notion/collection.py#L57

Example:
```
from notion.collection import NotionDate

a = NotionDate("Oct 11 2020")
```
Output:
```
Traceback (most recent call last):
  File "notion_tracker.py", line 14, in <module>
    row.date = a.to_notion()
  File "/home/dab/codes/notion_api/venv/lib/python3.8/site-packages/notion/collection.py", line 72, in to_notion
    start_date, start_time = self._format_datetime(self.start)
  File "/home/dab/codes/notion_api/venv/lib/python3.8/site-packages/notion/collection.py", line 57, in _format_datetime
    return date_or_datetime.strftime("%Y-%m-%d"), None
AttributeError: 'str' object has no attribute 'strftime'
```

Since that's the "text" shown in Notion in a Date column, I thought to fix it this way:

```
def _format_datetime(self, date_or_datetime):
        if not date_or_datetime:
            return None, None
        if isinstance(date_or_datetime, datetime):
            return (
                date_or_datetime.strftime("%Y-%m-%d"),
                date_or_datetime.strftime("%H:%M"),
            )
        else:
            #return date_or_datetime.strftime("%Y-%m-%d"), None
            return datetime.strptime(date_or_datetime, "%b %d %Y"), None
```

A better fix should be shipped in master.

**Comment by jamalex** [comment]
Thanks for the issue!

The NotionDate primarily expects actual datetime objects. It does allow one specific string date format, but I chose not to handle arbitrary date formats, as that can be a bit of a rabbithole. Instead, it would be best to pre-process dates from whatever source they're coming from, and then ensure they are already datetime objects before passing them in.
