### ISSUE TITLE
get_rows() returns empty result, but build_query().execute() is not

### ISSUE THREAD

**Issue by b0g3r** [jamalex/notion-py#21]
I have a simple notion database (in table view) and try to retrieve all rows. 
`collection_view.collection.get_rows` returns an empty list, but if I try to retrieve row with `collection_view.build_query().execute()` it working. I have this issue on a few tables, but other works well with get_rows.

Do you have any ideas about why it happens?

**Comment by b0g3r** [comment]
If it necessary for debugging purpose I can share the database public

**Comment by jamalex** [comment]
Hmm, I'm not able to replicate this locally. If you could share a specific table you're seeing this on, I can take a look.

**Comment by b0g3r** [comment]
Did you reproduce this case?

**Comment by jamalex** [comment]
Hmm, I'm unable to view the database -- it says:
>You do not have access to Bogers Home. Please contact an admin to add you as a member.

**Comment by jamalex** [comment]
Should be fixed by https://github.com/jamalex/notion-py/pull/82 which will be in an upcoming release.
