### ISSUE TITLE
t - Transaction

### ISSUE THREAD

**Issue by calibrationlaboratory** [jamalex/notion-py#213]
Good Afternoon, 

I was able to use the existing code and HTTP request to change a users permission on a page.  It works but I am not incorporating the transaction post request. 

I noticed that the end points were "t"
and then immediately followed by "SaveSubscriptions"

The "t" request has only "success".  

I tried looking through the JSON payload and didn't see anything that indicated it should be used in the "SaveSubscriptions" Post. 

I ran the SaveSubscriptions call with client.post, passing in the JSON payloads with changed UUIDs and values, it ended up working.

I guess I am just looking for any insight on what the "t" end point is doing and if it is necessary for this project?

- Jeff Breidigan
@ Calibration Laboratory

**Comment by jamalex** [comment]
It looks like the "t" requests are just for tracking purposes, and are not required in order for the actual operations to be completed.
