### ISSUE TITLE
How to query using a table's own view?

### ISSUE THREAD

**Issue by callzhang** [jamalex/notion-py#214]
How can we leverage table's own `view` for query purpose? I used `cv.default_query().execute()` but got all the result, not the view's result in notion.

**Comment by amaury-behague** [comment]
You can use `cv.build_query()` using the query of the view, which you can access using `cv.get("query2")` (I know it's written "query" in the README, but it didn't work for me, I used `cv.get()` to get all properties and realised it was "query2").

**Comment by callzhang** [comment]
That works like a charm! I used `result = cv.build_query(filter=cv.get('query2')['filter']).execute()` and got the default result from the view. Thanks!

**Comment by m-danya** [comment]
> `build_query(filter=cv.get('query2')['filter']).execute()`

Thanks! That's very useful, I've been trying to get the same thing for 20 minutes. 

This probably should be placed into README as an example
