### ISSUE TITLE
How to delete a row in a collection_view?

### ISSUE THREAD

**Issue by jdirocco** [jamalex/notion-py#216]
I would like to delete a row in collection.
```python
for row in cv.collection.get_rows():
     # HOW TO REMOVE THE row??
```

**Comment by jdirocco** [comment]
it is related to issue #37 .

**Comment by arturtamborski** [comment]
You should be able to remove it with `.remove()` method.

    for row in cv.collection.get_rows():
        row.remove(permanently=False or True)
