### ISSUE TITLE
Can I make client instance without token_v2 for public Notion page?

### ISSUE THREAD

**Issue by LeeJunHyun** [jamalex/notion-py#217]
I really appreciate your commitment to this project.  

To access private Notion pages, token_v2 is essential.

But when I want to get some information about public notion pages, the token is not needed.

How can I use it in this case?

**Comment by jamalex** [comment]
This is resolved by https://github.com/jamalex/notion-py/pull/123, which has been merged to master, and will be released to PyPI tonight.
