### ISSUE TITLE
Notion-py 0.0.27 has been released to PyPI

### ISSUE THREAD

**Issue by jamalex** [jamalex/notion-py#220]
After many delays (there's so much good stuff coming through, it's hard to set a cutoff), I finally released 0.0.27 to PyPI. Below, you can find a list of a few of the changes it includes (some of which were in the not-officially-released 0.0.26 as well). I know there's still a lot more to go through in the issues and PR's, but I didn't want to hold up this release any further. Thanks so much to all the contributions from the community!

If you'd like to support notion-py development, please consider [donating to my open-source nonprofit, Learning Equality](https://learningequality.org/donate/), since when I'm not working on notion-py, it probably means I'm heads-down fundraising for our global education work (bringing resources like Khan Academy to communities with no Internet). COVID has further amplified needs, with over a billion kids stuck at home, and over half of them without the connectivity they need for distance learning. You can now also [support our work via GitHub Sponsors](https://github.com/sponsors/learningequality)!

Updates include:

- Fix search parameter: https://github.com/jamalex/notion-py/pull/113
- Fix aggregation: https://github.com/jamalex/notion-py/pull/192
- Fix #92 (collection views being None): https://github.com/jamalex/notion-py/pull/96
- Allow disabling of view-updating when adding row: https://github.com/jamalex/notion-py/pull/104/commits/245bcaeb4cecde79e27e23ac22a4c49907bfa6e0
- Cope with missing destination in markdown links: https://github.com/jamalex/notion-py/pull/109 (thanks, @jean!)
- Remove status keyword to urllib3.Retry to maintain Python 3.5 compatibility: https://github.com/jamalex/notion-py/pull/121 (thanks, @hmartiro!)
- Enable "anonymous" (no token) access to public pages: https://github.com/jamalex/notion-py/pull/123 (thanks, @ttran!)
- Added "cover" attributes for Page blocks: https://github.com/jamalex/notion-py/pull/135 (thanks, @gabrocheleau!)
- Setup.py fixes to support new version of pip: https://github.com/jamalex/notion-py/pull/147 (thanks, @xnutsive!)
- Handle dashes embedded within links etc when converting from markdown: https://github.com/jamalex/notion-py/pull/158 (thanks, @cgamio!)
- Fix to getting media assets by passing in ID to signed URL: https://github.com/jamalex/notion-py/pull/185 (thanks, @ruucm!)
- Added set_user methods for multi account user: https://github.com/jamalex/notion-py/pull/218 (thanks, @shunyooo!)
- Fixed global searching ("search_blocks" plus new more general "search" method): https://github.com/jamalex/notion-py/commit/446da67ed991ee566e8bac560db13452c9559d07
- Allow easy locking and unlocking of pages and databases: https://github.com/jamalex/notion-py/commit/50dbecdb2884c8d49b78fc1040d52ca0f3fc6f38
- Adapt to renaming of created_by and last_updated_by properties: https://github.com/jamalex/notion-py/pull/181 (thanks, @Arsenal591!)

**Comment by AndreClaassen1** [comment]
Thank you for your great work. I have donated some money to your nonprofit organization. I have transformed Notion to a CMS with your api for my hugo driven website. I am very grateful. Thank you.

**Comment by ITAYC0HEN** [comment]
:tada: :tada: :tada: :tada: 
I think it can be a very nice idea to use Github's release feature to note down the changelog. It will be easier to access recent changelogs and will notify people who watch the repository only for Releases
