### ISSUE TITLE
Can't write value to NotionDate type object

### ISSUE THREAD

**Issue by Cyberpuncrush** [jamalex/notion-py#230]
I can get NotionDate type object and it's value '.start', '.end' easilly with:

client = NotionClient([token_notion])
row = client.get_block([url_to_block_in_a_database])
print(row.start)
print(row.end)

however, I can never change the value of it, do I have any way to write value into NotionDate type object ? It's important for me.

Hope you can feedback!

**Comment by mikkorov** [comment]
NotionDate type object requires a datetime object. I am no expert but the following has worked for me:

from datetime import datetime
datetime_object = datetime.strptime('date_in_string_format', '%d-%m-%Y %H:%M:%S')
then pass datetime_object to your desired NotionDate object.

More on datetime here:
https://docs.python.org/3/library/datetime.html

**Comment by Cyberpuncrush** [comment]
> NotionDate type object requires a datetime object. I am no expert but the following has worked for me:
> 
> from datetime import datetime
> datetime_object = datetime.strptime('date_in_string_format', '%d-%m-%Y %H:%M:%S')
> then pass datetime_object to your desired NotionDate object.
> 
> More on datetime here:
> https://docs.python.org/3/library/datetime.html

Thanks, it works!🤩

**Comment by Cyberpuncrush** [comment]
> NotionDate type object requires a datetime object. I am no expert but the following has worked for me:
> 
> from datetime import datetime
> datetime_object = datetime.strptime('date_in_string_format', '%d-%m-%Y %H:%M:%S')
> then pass datetime_object to your desired NotionDate object.
> 
> More on datetime here:
> https://docs.python.org/3/library/datetime.html

I've tried to assign a start datetime for NotionDate object, and it works:

from datetime import datetime
datetime_object = datetime.strptime('date_in_string_format', '%d-%m-%Y %H:%M:%S')
client = NotionClient([token_notion])
row = client.get_block([url_to_block_in_a_database])
row.Date = datetime_object

but is it possible to assign both start and end date for NotionDate object?😥 like assign time for an event in calendar

**Comment by mikkorov** [comment]
I had a look at it a week ago but couldn't figure it out... one option for you could be to use 2 different NotionDate object (1 for start and 1 for end)...

**Comment by Cyberpuncrush** [comment]
> I had a look at it a week ago but couldn't figure it out... one option for you could be to use 2 different NotionDate object (1 for start and 1 for end)...

seems doesn't work... I tried to assign start and end datetime like:

from datetime import datetime
datetime_object_start = datetime.strptime('2020-12-2 23:20:20', '%d-%m-%Y %H:%M:%S')
datetime_object_end = datetime.strptime('2020-12-4 23:20:20', '%d-%m-%Y %H:%M:%S')
client = NotionClient([token_notion])
row = client.get_block([url_to_block_in_a_database])
row.Date.start = datetime_object.start
row.Date.end = datetime_object.end

but both start and end date has not changed in this way...😣

however, you can output start and end date with row.Date.start and row.Date.end if you assigned on notion.so webpage...

**Comment by Cyberpuncrush** [comment]
> I had a look at it a week ago but couldn't figure it out... one option for you could be to use 2 different NotionDate object (1 for start and 1 for end)...

I read code and find a way works, like:

from notion.collection import NotionDate
datetime_object_start = datetime.strptime('2020-12-2 23:20:20', '%d-%m-%Y %H:%M:%S')
datetime_object_end = datetime.strptime('2020-12-4 23:20:20', '%d-%m-%Y %H:%M:%S')

obj_notion = NotionDate(start= datetime_object_start, end= datetime_object_end)

client = NotionClient([token_notion])
row = client.get_block([url_to_block_in_a_database])
row.Date = obj_notion

It just works!!!😆
