### ISSUE TITLE
QUESTION - Is there a way to add a property to an already existing collection?

### ISSUE THREAD

**Issue by corode** [jamalex/notion-py#242]
I don't know where else to ask, I was wondering how you can add a property to an existing collection?

**Comment by corode** [comment]
I found the answer myself:

If you edit the data structure of a block/collection, then you can sync it to notion using set, i.e. to add a new property:
```python
cvb = client.get_block(collection_view_block_url)

# inserts a new property into the cached dictionary
cvb.collection.get()['schema']['NewProp'] = {
    "name": 'New property',
    "type": 'text'
}

# loads the cached schema into a variable to make it easier to manipulate
schema = cvb.collection.get()['schema']

# syncs the locally cached schema to the notion server
cvb.collection.set(path=['schema'], value=schema)
```

N.B. if you add ```force_refresh=True``` in the get method *before* you set the dictionary, you will get the original i.e. the one stored in the actual notion database, not the cached one. Until you use ```set()```, the structure/collection/block is not updated.

**Comment by ag0n1k** [comment]
#274 added more clear interface to create property
