### ISSUE TITLE
400 Error when initializing client

### ISSUE THREAD

**Issue by aivantg** [jamalex/notion-py#251]
Started getting this error when I tried running a script that had worked in the past. I've confirmed the Notion token is accurate, and the path to the notion library is a local directory but it contains the latest copy of the code. Any ideas if this is due to an API change on Notion's end or something? 

```
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    client = NotionClient(token_v2=NOTION_TOKEN)
  File "/Users/aivant/Development/Projects/Primer/parser/notion/client.py", line 76, in __init__
    self._update_user_info()
  File "/Users/aivant/Development/Projects/Primer/parser/notion/client.py", line 82, in _update_user_info
    records = self.post("loadUserContent", {}).json()["recordMap"]
  File "/Users/aivant/Development/Projects/Primer/parser/notion/client.py", line 211, in post
    "message", "There was an error (400) submitting the request."
requests.exceptions.HTTPError: Something went wrong.
```

**Comment by jjerry-k** [comment]
I have same issue!

If Notion use AWS, I am suspicious about AWS...

https://status.notion.so

**Comment by aivantg** [comment]
Yup, was an issue on Notion's side. Resolved for me now.

**Comment by AndreClaassen1** [comment]
I have the same issue. Ok, I have thought, I have done something wrong.

**Comment by mixeden** [comment]
+1

**Comment by mixeden** [comment]
Seems to be fixed now

**Comment by AndreClaassen1** [comment]
Yes. We can close this issue now. All things are working fine. For a (long) moment I have thought, that I have destroyed the Notion Servers with my latest coding.
