### ISSUE TITLE
SyntaxError: "from notion.client import NotionClient"

### ISSUE THREAD

**Issue by chcgnzls** [jamalex/notion-py#256]
Fresh install of notion from pip on macos catalina 10.15.7 using python 3.5.4

```
Python 3.5.4 (v3.5.4:3f56838976, Aug  7 2017, 12:56:33) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from notion.client import NotionClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/checo/pyenv/notion/lib/python3.5/site-packages/notion/client.py", line 103
    raise Exception(f"Not Found {email}, Available IDs: {list(email_uid_dict)}")
                                                                              ^
SyntaxError: invalid syntax
>>> 
```

**Comment by c-schaer** [comment]
Getting the same error. Looks like you can't use an f-string in an Exception like that, so it throws a syntax error. At least, that is my suspicion after only a couple minutes of looking at it

**Comment by jamalex** [comment]
Thanks for flagging -- I hadn't realized that f-strings were only added in Python 3.6, and @chcgnzls is using 3.5.4. We aim (and claim) to support 3.5+, so this was important to fix.

I've merged @c-schaer's [PR](https://github.com/jamalex/notion-py/pull/258) (thanks!) and added [an additional commit](https://github.com/jamalex/notion-py/commit/34b8729175412a0d26e7bfd2f4c9138791f801bc) so we still get a useful exception message.
