### ISSUE TITLE
Can I get properties in order?

### ISSUE THREAD

**Issue by TheStarkor** [jamalex/notion-py#264]
Thanks for sharing the awesome library.

Here is my code
```python
cv = client.get_collection_view(<URL>)

for property in cv.collection.get_schema_properties():
    print(property)
```

The table is
![image](https://user-images.githubusercontent.com/45455072/106128024-67dc0200-61a2-11eb-9eda-600093f5d9d2.png)

result is 
```
{'id': '^j]X', 'slug': 'bbb', 'name': 'bbb', 'type': 'text'}
{'id': 'bP[^', 'slug': 'aa', 'name': 'aa', 'type': 'text'}
{'id': 'v;hb', 'slug': 'tags', 'name': 'Tags', 'type': 'multi_select'}
{'id': 'title', 'slug': 'name', 'name': 'Name', 'type': 'title'}
```

I want to get properties in order like
```
Name, Tags, bbb, aa
```

Is there any method that can get properties in order?

**Comment by younho9** [comment]
`cv.get("format.table_properties")`return the `width`, `visible`, `property` of column in the collection view in order.

By filtering `cv.collection.get_schema_properties()` by the `property` name obtained here, properties can be obtained in order.

```python
def get_ordered_properties():
    cv = client.get_collection_view(<URL>)
    tp = cv.get("format.table_properties")
    sp = cv.collection.get_schema_properties()
    
    properties = []

    for tp_item in tp:
            properties += list(
                filter(lambda sp_item: sp_item["id"] == tp_item["property"], sp)
            )

    return properties
```

**Comment by TheStarkor** [comment]
@younho9 Wow, thanks!!!

I have a new problem. Can you help me? #282
