### ISSUE TITLE
Setting reminders to NotionDate

### ISSUE THREAD

**Issue by athossampayo** [jamalex/notion-py#276]
I did some testing and managed to set reminders to NotionDate class, so the user can set when they want to be reminded of the Due Date. Actually is possible to set reminders even for different times before the date than the Notion app permits (On the app or website you have predifined dates to set, and is possible to set it to 10 days before, for example)
I'm willing to make an PR for adding this function, but wanted to know if I show add a `NotionDate.set_reminder()` function or structure it in another way? Any tips?

**Comment by ITAYC0HEN** [comment]
Hey! Very nice initiative :) I am not the maintainer but it sounds good to me to use `.set_reminder(...)`.
I suggest sending a pull-request, mark it as `Draft`, and put your questions and work-in-progress in there. Issues are not the best place to discuss dev topics.

Another option is to use the [Discussions](https://github.com/jamalex/notion-py/discussions) tab :0

**Comment by athossampayo** [comment]
Oh I did not have any experience with the [Discussions](https://github.com/jamalex/notion-py/discussions) tab yet, even forgot it existed! Thanks, will start working on a Draft PR and lets see what I can do. 

Cheers 😄
