### ISSUE TITLE
Updating property values in collection faster

### ISSUE THREAD

**Issue by RenanBomtempo** [jamalex/notion-py#289]
I have a database with 46 properties, and sometimes I need to set a value for each of them. Right now I'm setting them one by one for each row. But it takes from 20 to 60 seconds to set all properties for each row. 
Is there a faster way to set these property values? Maybe some sort of batch functionality to use a single API call instead of one `set_property()` for each value to be set?

**Comment by AndreClaassen1** [comment]
use the with clause with client.as_atomic_transacton()

here is a example from my code:

       with self._client.as_atomic_transaction():
            for key, val in kwargs.items():
                setattr(row, key, val)

            if update_views:
                # make sure the new record is inserted at the end of each view
                for view in self.parent.views:
                    if view is None or isinstance(view, CalendarView):
                        continue
                    view.set("page_sort", view.get("page_sort", []) + [row_id])

**Comment by RenanBomtempo** [comment]
That is exactly what I needed! Thank you so much Andre!
