### ISSUE TITLE
Is there a way to retrieve or change the cover of a page?

### ISSUE THREAD

**Issue by DandyDev** [jamalex/notion-py#29]
I would like to create new items in a database, and for the items I create, I'd like to set a cover. Is this possible? I can't find it in the documentation or code.

**Comment by DandyDev** [comment]
Never mind, found it. Cover can be retrieved as such:
```python
page.get("format.cover")
```
and be set as such:
```python
page.set("format.cover", "http://link.to/my_image.jpg")
```

Maybe good to document it?

**Comment by jamalex** [comment]
Glad you found it! There are a lot of these types of things, so I didn't try to document everything. If you see a good place to add it to the examples or docs, would welcome a quick PR! Thanks!

**Comment by OdysLam** [comment]
Hey, I have a weird issue. API seems to change the cover (I print the field after I set it) but in Notion the cover doesn't change.

**Comment by ndrewwang** [comment]
Hey @OdysLam  

I ran into the same issue, instead of `.icon `and `.cover`

it should be: 

```
page.get("format.page_cover")

page.set("format.page_cover", "http://link.to/my_image.jpg")
```
