### ISSUE TITLE
How can I get a sharable url of a new page created by API?

### ISSUE THREAD

**Issue by insanebear** [jamalex/notion-py#298]
Hi.

I want to get a sharable url of a new page created or found by API.
Like,
- There is a parent Notion page and I use a sharable url of it which I got from web browser to get a block_id.
- I create a new page in the parent page using API.
- I want to open this new page on web browser.

I looked through util.py, but I guess there are only functions for converting url to block_id.
Could anyone guide me?

**Comment by fedeserbin** [comment]
Hi. We use notion_object.get_browseable_url()
Hope this works for you.

**Comment by insanebear** [comment]
@fedeserbin Why couldn't I find it?! 😭 Thank you so much :D
