### ISSUE TITLE
get_rows(search=...) doesn't work

### ISSUE THREAD

**Issue by DandyDev** [jamalex/notion-py#30]
In the [README it says](https://github.com/jamalex/notion-py/blame/master/README.md#L133) you can search on a collection by passing the `search` keyword argument. This doesn't work anymore. After looking at the commit-history, it seems this functionality was removed in https://github.com/jamalex/notion-py/commit/e5aa1b0839937cf3f96bd7b932537a916880ec84#diff-ff227cb3ca5f6b2999b69d70551f639a

What is the new way of searching through a collection?

**Comment by vinceblake** [comment]
Ok, did some playing around and figured this out (I think). It _looks_ to me like the new design is to build a "query" before executing it (which returns the results of that query). It is also worth noting that there is a programmatic difference between a collection and a collection_view. I was unsuccessful in querying for the collection itself, but getting a view and then retrieving the parent collection seems to work well.

from notion.client import NotionClient
from notion.collection import *

client = NotionClient(token_v2="[your token_v2]")
cv = client.get_collection_view("[link to your collection view]")
q = CollectionQuery(cv.collection, cv, "your query goes here")
for res in q.execute():
    [do stuff]

**Comment by DandyDev** [comment]
Thanks for figuring that out. I will try it this weekend and see if it works for me as well

**Comment by nicholasurban** [comment]
> q = CollectionQuery(cv.collection, cv, "[your query goes here]")

Yep, that works for me!

**Comment by jamalex** [comment]
Thanks for documenting the workaround here! The original approach should once again be enabled in an upcoming release via https://github.com/jamalex/notion-py/pull/82, also.

**Comment by Vafa-Andalibi** [comment]
Can we have an example of the query `[your query goes here]` ?
