### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by 0nliner** [jamalex/notion-py#309]
Hello. I trying using token_v2 for authentication, but it doesn't work for me.
My code:

```

    token: str = "token_v2_value_from_cookies",
    link = "https://www.notion.so/f8415b83abfb4fd3963a60f53874b2af"

    # token: str = sys.argv[0]
    # link: str = sys.argv[1]

    client = NotionClient(token_v2=token)

    fullyConvert(link="https://www.notion.so/f8415b83abfb4fd3963a60f53874b2af",
                 client=client
                 )

```
Where I got token value

![image](https://user-images.githubusercontent.com/78047335/113019836-ac781f80-918a-11eb-9a7f-db1d615ad870.png)

**Comment by laertemeira** [comment]
Hello,

Maybe it works (is working for me):

(Put your token n URL instead my ones)

from notion.client import NotionClient

NOtaskTestURL = 'https://www.notion.so/c4cba60f8e2c4f5885242a3f72f736fd?v=f2b5xyz4a4234fb0b341217885dfb193'
NOtoken     = '44bf91b119e0a6185601d66b68f65dca1498a0d1ea9c32db18e915356df632113bebb605ffaf315609cab0589c6a83f8d97f350feeba4506309aedc4c9393d4a76c588c2e58xyz6b73c4811bd24e'

NOclient    = NotionClient(token_v2 = NOtoken)
NOcollectionTest = NOclient.get_collection_view(NOtaskTestURL)
