### ISSUE TITLE
Get signed attachment url

### ISSUE THREAD

**Issue by patrickjm** [jamalex/notion-py#311]
If you've uploaded an attachment to Notion and it created a BookmarkBlock with a `link` value pointing to your AWS attachment, to download it, you need to call an extra endpoint to get the secure URL.

```python
urls = block._client.post(
        "getSignedFileUrls",
        { "urls": [{
          "url": block.link,
          "permissionRecord": {
            "id": block.id,
            "table": "block"
          }
        }] }
      ).json()
url = urls["signedUrls"][0]
```

**Comment by ruucm** [comment]
thanks a lot to sharing this!
