### ISSUE TITLE
Add global search capabilities

### ISSUE THREAD

**Issue by kevinjalbert** [jamalex/notion-py#32]
I am interested if we can add the ability to programatically _search_ (like cmd/ctrl + p) through all block. I checked and there is a specific API call (`https://www.notion.so/api/v3/searchBlocks`) that is used, although the output is a little more puzzling on how it narrows down to the shown content.

It would be neat to some how surface the block's title/type and the content (much like how the search modal works now).

**Comment by jamalex** [comment]
Wish (finally) granted! Will be part of upcoming release via https://github.com/jamalex/notion-py/pull/83
