### ISSUE TITLE
Is there a way to get ToggleBlock's status

### ISSUE THREAD

**Issue by kaedea** [jamalex/notion-py#328]
For the following example, getting:
ToggleBlock1's status = open
ToggleBlock2's status = close/default

![image](https://user-images.githubusercontent.com/3963397/118444063-425a1080-b71f-11eb-95e7-d39c18e9afce.png)

**Comment by vintlucky777** [comment]
it's not available for editing in Notion.
you can test it like so:
 - creating a page with a few toggles - some open, some closed
 - share the page to web, copy link
 - open that link in your browser's Incognito mode
 - see that all Toggles appear closed initially. after that, your browser will remember toggle status between refreshes, but that state is stored in local_storage and will be wiped when the cache is cleaned or incognito session is closed.

<img width="1586" alt="Some page 2021-06-07 16-27-08" src="https://user-images.githubusercontent.com/3831006/121099767-4f61a100-c7ad-11eb-9f77-448ea1c2769d.png">
