### ISSUE TITLE
Collection column/property order and hide status

### ISSUE THREAD

**Issue by AlainRo** [jamalex/notion-py#34]
How can I get the display order of a table properties/columns ? And hide status ?
When accessing a View 
 * get_all_properties() is not ordered
 * schema doesn't have any index or order 

Am I missing something ?

PS: Great work. Thanks very much.

**Comment by kappa-london** [comment]
You can parse the properties with A json parser -> som of them do have optional parameters to order / sort etc.

**Comment by jamalex** [comment]
The table-view-specific sort order and hide/show status are stored on the view itself, under "format.table_properties". You can do things like the following:

```
cv = client.get_collection_view("https://www.notion.so/...")
tp = cv.get("format.table_properties")
tp[4]["visible"] = False
cv.set("format.table_properties", tp)
```
(and similarly, you can reorder the items in the list and do a `set` again)

The property id's aren't human-readable, but you can cross-reference with `cv.collection.get_schema_properties()` to look them up based on slugs.
