### ISSUE TITLE
requests.exceptions.HTTPError: Invalid input.

### ISSUE THREAD

**Issue by 7k50** [jamalex/notion-py#343]
I am trying out notion-py for the first time, but actually can't get it to run the [Quickstart](https://github.com/jamalex/notion-py#quickstart) example.

I installed for Pyton 3.9 via `pip install notion` with version 0.0.28.

```
from notion.block import TweetBlock
client = NotionClient(token_v2="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
page = client.get_block("https://www.notion.so/myorg/Test-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
print("The old title is:", page.title)
```

Gives:

```
Traceback (most recent call last):
  File "…/test_notion-py.py", line 35, in <module>
    page = client.get_block("https://www.notion.so/myorg/Test-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
  File "…/lib/python3.9/site-packages/notion/client.py", line 169, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "…/lib/python3.9/site-packages/notion/client.py", line 162, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "…/lib/python3.9/site-packages/notion/store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "…/lib/python3.9/site-packages/notion/store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "…/lib/python3.9/site-packages/notion/client.py", line 260, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.
```

**Comment by ashleymavericks** [comment]
I'm also facing the same issue! But I saw this issue was opened a year back as well, and the solution was merged back then.

**Comment by felipehlvo** [comment]
I have the same issue

**Comment by 7k50** [comment]
This is apparently a known issue that has a "fix". I don't know if the fix is temporary or permanent. It hasn't been merged into the main release yet.

See: https://github.com/jamalex/notion-py/pull/294#issuecomment-804306525

**Quick solution**

Uninstall current version if required:

`pip uninstall notion`

Then:

`pip install git+https://github.com/jamalex/notion-py.git@refs/pull/294/merge`

OR add into _requirements.txt_:

`git+https://github.com/jamalex/notion-py.git@refs/pull/294/merge`

**Comment by annahung31** [comment]
Hi, I've already reinstalled notion with `pip install git+https://github.com/jamalex/notion-py.git@refs/pull/294/merge`, but I still faced the same error. 
Is there any other way to solve this? 
Thanks!

**Comment by dazaooo** [comment]
i slove this problem

`pip uninstall notion`

`pip install git+https://github.com/jamalex/notion-py.git@refs/pull/294/merge`
