### ISSUE TITLE
Polling is broken

### ISSUE THREAD

**Issue by apollovy** [jamalex/notion-py#36]
Hi.First, thank you for the library, very helpful!
Second, I was experiencing lines in a log like
`2019-06-24 01:43:26,076 - ERROR - Persistent error submitting polling request: b'{"code":1,"message":"Session ID unknown"}' / 400 Client Error: Bad Request for url: https://msgstore.www.notion.so/primus/?sessionId=SESSION_ID&EIO=3&transport=polling&sid=SID (will retry 5 more times)`

Also, CPU was always 100% busy and I saw that caching was working in a very strange manner. Looked like the data was constantly re-written: I monitored the sizes of cache files, and they were growing to some point, then reset back to zero and then the growth repeated with the reset in the end and so on. My system monitoring shown that for about an hour the amount of data the process written to disk was about 15 gigs, but no such network activity was seen for this process at the same time.

When I restarted the shell and created a client with
`    monitor=False,`
this stopped and everything went fine.

**Comment by indirectlylit** [comment]
I can confirm that this behavior is happening consistently when using the client in `ipython` with monitoring enabled.

**Comment by jamalex** [comment]
Thanks, I can replicate monitoring not working. I'll be looking into it here shortly.

**Comment by jamalex** [comment]
Actually, further testing shows monitoring to be working fine for me. The CPU/file growing issues were most likely just cache-related, and I've now disabled the file cache by default. The "Persistent error submitting polling" log entry has always happened, and I was never able to avoid it, but internally it recreates a new session and picks up where it left off -- the polling session ID just seems to get invalidated randomly at times. When the session expires in this way, there will be a slight lag in updating records (a few seconds), but nothing should be missed.

Could you test again using newly released 0.0.25, initializing your session with
`client = NotionClient(token_v2=token_v2, monitor=True, start_monitoring=True)`?

Thanks!

**Comment by bevinhex** [comment]
after adding `monitor=True, start_monitoring=True` , I can get latest records

**Comment by jean** [comment]
@apollovy can this issue be closed?

**Comment by apollovy** [comment]
Hopefully yes, frankly I lost my interest to the library, sorry.
