### ISSUE TITLE
Is there a quick way to extract all rows from table with column data?

### ISSUE THREAD

**Issue by b0g3r** [jamalex/notion-py#42]
Now I use something like that:
```python
client.get_collection_view(collection_view_url)
all_rows = list(collection_view.build_query().execute())
all_rows_data = [row.get_all_properties() for row in all_rows]
```

But it's extremely slow (~1m for each row). Are there any other ways to do it?

**Comment by jamalex** [comment]
This should now be very fast, after the updates in 0.0.24 and 0.0.25 -- please re-open if it's still slow for you! Thanks.
