### ISSUE TITLE
when I add cv's row , why can't I insert property 

### ISSUE THREAD

**Issue by M0nk2ySion** [jamalex/notion-py#44]
![image](https://user-images.githubusercontent.com/47164302/62694988-6055f580-ba10-11e9-9faf-c3c4d2db59e2.png)

    row = cv.collection.add_row()
    row.name = 'name'
    row.Status = 'New'
    row.title = 'why'

when I run this code, cv's row added normal 
but property didn't insert Why??

**Comment by M0nk2ySion** [comment]
I Confirm Success when I change property's name to lower case
Why Can't use upper case

**Comment by jamalex** [comment]
The property names, when accessed as attributes on the record instance, are "slugified", which makes them lowercase and replaces special characters and spaces with "_".

To make it a bit more tolerant, I've added some normalization code in https://github.com/jamalex/notion-py/pull/88 that will go into an upcoming release, which will allow varied case when setting attributes.
