### ISSUE TITLE
Views in collection view blocks are not ready to have filters added immediately after creation

### ISSUE THREAD

**Issue by indirectlylit** [jamalex/notion-py#46]
ref: https://github.com/jamalex/notion-py/pull/38#discussion_r315471514

After creating and adding a new `collection_view` to a `CollectionViewBlock`, one must wait a second or two before setting additional properties such as queries. Attempting to set these properties without waiting throws an error, but does not persist the change.

**Comment by jamalex** [comment]
I was unable to replicate this with the `time.sleep(3)` commented out, so I'm hoping it's been fixed on the server side. For now, I've removed the sleep in https://github.com/jamalex/notion-py/pull/89 -- if the issue recurs in the new version, please post a code sample here and re-open.
