### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by midnightmastermind** [jamalex/notion-py#48]
So I've been messing around with changing color. 

`
page = client.get_block("https://www.notion.so/598d04a5d54a40d3b93637f158420039")
page.set('format.block_color', 'green_background')`

I haven't tried every color, but it seems that most of them are working except 'green' and 'green_background'

Any advice?

**Comment by lbogdan** [comment]
It's actually `teal` (I peeked at the API call payload while changing the color to green in the webapp).

**Comment by jamalex** [comment]
Thanks for the tip, @lbogdan!
