### ISSUE TITLE
API to get the pages hierarchy

### ISSUE THREAD

**Issue by mabead** [jamalex/notion-py#50]
I am looking for a way to get the list of all the pages in my notion space as well as their place in the hierarchy. I started by calling the `client.get_space` and then using the resulting `pages` field:

```python
# pip install notion
from notion.client import NotionClient

client = NotionClient(token_v2="some_token")

space = client.get_space('my_space_id')

for page_id in space.pages:
    page = client.get_block(page_id)
    print(page.title)
```
Now that I get all the childs of my root/space, is there a way to continue the recursion and get the child sub pages?

**Comment by eoranged** [comment]
You can use [a snippet from Readme](https://github.com/jamalex/notion-py#example-traversing-the-block-tree) for each page:
```
for page_id in space.pages:
    page = client.get_block(page_id)
    print(page.title)
    for child in page.children:
        print(child.title)
```

**Comment by eoranged** [comment]
After digging a bit deeper, I found that this is not enough.
What you need is to call `client.post("loadUserContent", {}).json()["recordMap"]["block"].keys()` to fetch ids of all pages and then iterate through all the children blocks of types 'page' and 'collection'. Maybe there are more block types that displayed as pages (like collection_view), but I didn't need them for my task.
This is a dirty and inefficient but working example of how to do this — https://github.com/eoranged/notion-scripts/blob/master/audit.py

**Comment by jamalex** [comment]
I've added a `client.get_top_level_pages` method in https://github.com/jamalex/notion-py/pull/87 based on @eoranged's code suggestion. This will be released soon in a new version.

For the recursion, you can just use standard recursion to loop down through the descendants to do whatever you like with them. For example:

```
def recursively_print_titles(block, depth=0):
	print("\t" * depth + block.title)
	for child in block.children:
		recursively_print_titles(child, depth=depth+1)

for block in client.get_top_level_pages():
    recursively_print_titles(block)
```
(but it's going to be slowwwww, if you have a ton of pages)

**Comment by odusseys** [comment]
I believe this get_top_level_pages method is broken. It's pretty tough to replicate but I am getting plenty of pages which are not top-level pages in some cases (as attested by the fact that the parent_table is not 'space'). I think it needs a check on the parent_table to work (would also be interested to know why it loads so many more unneccessary blocks already).

**Comment by rishabhjaiz** [comment]
Is there a way for an third party app integration to access list of all page ids?
