### ISSUE TITLE
API to create new select item

### ISSUE THREAD

**Issue by aqzas** [jamalex/notion-py#51]
I want to add some new select item/tag to the select/multi-select property of a page. Is there anyway to do that ?

**Comment by bkiac** [comment]
Maybe not the most efficient but I've used the set schema method to implement this for myself with the following code:
```python
from uuid import uuid1 as uuid
from random import choice

from notion.client import NotionClient

notion_client = NotionClient(token_v2=NOTION_TOKEN)
collection_view = notion_client.get_collection_view(NOTION_PAGE)
collection = collection_view.collection

colors = [
    "default",
    "gray",
    "brown",
    "orange",
    "yellow",
    "green",
    "blue",
    "purple",
    "pink",
    "red",
]

def add_new_multi_select_value(prop, value, color=choice(colors)):
    collection_schema = collection.get("schema")
    prop_schema = next(
        (v for k, v in collection_schema.items() if v["name"] == prop), None
    )
    if not prop_schema:
        raise ValueError(
            f'"{prop}" property does not exist on the collection!'
        )
    if prop_schema["type"] != "multi_select":
        raise ValueError(f'"{prop}" is not a multi select property!')

    dupe = next(
        (o for o in prop_schema["options"] if o["value"] == value), None
    )
    if dupe:
        raise ValueError(f'"{value}" already exists in the schema!')

    prop_schema["options"].append(
        {"id": str(uuid1()), "value": value, "color": color}
    )
    collection.set("schema", collection_schema)
```
Tagging #28 for duplicate.

**Comment by callixte-girard** [comment]
Hi,
I'm encountering the same problem as you. Thanks for your code.
But it's not working for me. It doesn't recognise `prop_schema["options"]`. Do you have an idea why ?

**Comment by callixte-girard** [comment]
Okay so I managed to fix it. I think there were two problems :
1) I needed to add `force_refresh=True` to the line where I get the collection view, like this :
`.get_collection_view(collection_url, force_refresh=True)`, because it was not refreshing correctly.
2) I needed to create the `options` field if it didn't exist, like this : 
`if "options" not in prop_schema: prop_schema["options"] = []`
Hope it helps !

**Comment by nagamotoK** [comment]
Caution: running this crashed my table (beyond repair?). All I get now is the "oops! something went wrong"- page when I try to access it

**Comment by bkiac** [comment]
@nagamotoK That is weird, I still use a slight changed version of this in my [bot](https://github.com/bkiac/wickie/blob/173fbfd4660ca5ac9107a67f3a87a588c58de000/wickie/notionutils/add.py#L35) every day.

**Comment by nagamotoK** [comment]
@bkiac thank you for the link/code. It seems, that the error was on my side. I used your implementation and now it works --

**Comment by Eldhrimer** [comment]
Hello, I've tried to use it to create new select properties but  i can't seem to get it working. Any clues for a newbie?

**Comment by jamalex** [comment]
Automatic adding of missing options is now merged via https://github.com/jamalex/notion-py/pull/252
