### ISSUE TITLE
collection.get_rows() returns nothing

### ISSUE THREAD

**Issue by dansteingart** [jamalex/notion-py#52]
Thanks in advance for a great package. I am having a challenge where `collection.get_rows()` is returning nothing when the table has rows. The schema shows up, but the data does not. It seems to only be an issue for recently made tables (less than a day old). Older tables I get the rows ~70% of the time.

**Comment by dansteingart** [comment]
FWIW here's a workaround:

```
ids = collection_block.views[0].get()['page_sort']
rows = []
for id in ids: rows.append(client.get_block(id))
```

This returns the correct information 100% of the time.

**Comment by bkiac** [comment]
Same problem for me, it looks like something changed recently in the Notion API because I noticed that newly added schema objects have different fields

**Comment by Gaspero** [comment]
> FWIW here's a workaround:
> 
> ```
> ids = collection_block.views[0].get()['page_sort']
> rows = []
> for id in ids: rows.append(client.get_block(id))
> ```
> 
> This returns the correct information 100% of the time.

I faced the same problem and also found a workaround. Another option is to use
`result = cv.default_query().execute()`

**Comment by Cobertos** [comment]
This doesn't seem to be working for me, the `views` array is returning `None`.

```
>>> cv.views
[
  None,
]
```

**Comment by jamalex** [comment]
Should be fixed by https://github.com/jamalex/notion-py/pull/82, which will be released in an imminent version.
