### ISSUE TITLE
collection.get_rows(search="") got TypeError: get_rows() got an unexpected keyword argument 'search' 

### ISSUE THREAD

**Issue by Marila** [jamalex/notion-py#55]
as title

**Comment by swanv** [comment]
me too

**Comment by arapl3y** [comment]
+1

**Comment by nabilridhwan** [comment]
From what I see in the `collection` class:
get_rows was not expecting the `search` argument, maybe this was removed on release because of bugs?

```javascript
    def get_rows(self):
        rows = []
        for row_id in self._client._store.get_collection_rows(self.id):
            row = self._client.get_block(row_id)
            row.__dict__["collection"] = self
            rows.append(row)
        return rows
````

**Comment by nabilridhwan** [comment]
So, i created a temporary fix: https://github.com/jamalex/notion-py/pull/73 . However just note that if you were to use my fork, you'll have to manually get it inside your project file.

**Comment by Cobertos** [comment]
Might also refer to this issue:
https://github.com/jamalex/notion-py/issues/30

**Comment by jamalex** [comment]
Old approach should be reinstated by https://github.com/jamalex/notion-py/pull/82 which will be in an upcoming release.
