### ISSUE TITLE
Can programmatically disable logging using FileHandler

### ISSUE THREAD

**Issue by z-jason** [jamalex/notion-py#56]
Use Case: I tried to run notion-py on Lambda and there is an error. The error is caused by the notion-py logger trying to write to disk. I resolved the error by replacing logging.FileHandler with logging.NullHandler. It would be nice if we can configure log setting programatically.

**Comment by jamalex** [comment]
Good idea. Addressed in https://github.com/jamalex/notion-py/pull/86 through an environment variable approach. Will be released in an upcoming version.
