### ISSUE TITLE
Files not accessible

### ISSUE THREAD

**Issue by jajoosam** [jamalex/notion-py#59]
When I try reading a file field from a collection, it returns a URL.

When I visit this url, I get this error:
![image](https://user-images.githubusercontent.com/10261910/67154567-311b0900-f31c-11e9-8370-bce692a1d021.png)

**Comment by fmartingr** [comment]
Not sure if you're still having trouble, but you just need to prepend `https://notion.so/image/` to the provided URL.

**Comment by jajoosam** [comment]
Ah I see. Thanks!
