### ISSUE TITLE
Add new row to collection with Date property value

### ISSUE THREAD

**Issue by colinxr** [jamalex/notion-py#65]
I'm trying to create a new row in a collection. The collection has a column called 'last_contact' which is a date field. I'm not having any luck passing in a value for the `row.last_contact`. I've gone through the `smoke_test.py`, but haven't seen any examples in there. Likewise, I've looked at the `collection.py` file, at the NotionDate class in particular, but still haven't seen anything.

What's the best way to add a date field to a new row?

**Comment by colinxr** [comment]
Closing this issue. Was able to pass in a date object into the a new NotionDate object which could then be added to the row using `row.last_contact`.

**Comment by raphodn** [comment]
I faced the same issue, and needed to add the current date (without time) to the row. The column in my table is called `created`. Here's some code that works:

```
from datetime import datetime, date

client = NotionClient(token_v2=<INSERT_YOUR_TOKEN>)
table = client.get_collection_view("https://www.notion.so/<INSERT_YOUR_STRING>")

row = table.collection.add_row()
row.created = notion.collection.NotionDate(date.today())
# row.created = notion.collection.NotionDate(date(2020, 1, 1)) # this also works
```

**Comment by Cyberpuncrush** [comment]
> I faced the same issue, and needed to add the current date (with or without time) to the row. The column in my table is called `created`. Here's some code that works:
> 
> ```
> from datetime import datetime, date
> 
> client = NotionClient(token_v2=<INSERT_YOUR_TOKEN>)
> table = client.get_collection_view("https://www.notion.so/<INSERT_YOUR_STRING>")
> 
> row = table.collection.add_row()
> row.created = notion.collection.NotionDate(date.today()) # date without time
> # row.created = notion.collection.NotionDate(date(2020, 1, 1)) # date without time (this also works)
> # row.created = notion.collection.NotionDate(datetime.now()) # date with time
> ```

Is it possible to assign both start and end date?
