### ISSUE TITLE
Normalised option for get_all_properties()

### ISSUE THREAD

**Issue by kappa-london** [jamalex/notion-py#69]
Would be fairly useful to allow .get_all_properties() the possibility of passing parameters in regards how certain default fields to be handled: such as User class to be always interpreted and converted to User.full_name(). 

Is it possible under the current format ?

Kind Regards

**Comment by jamalex** [comment]
Hi @kappa-london. This is not currently possible by passing arguments, but could be handled well with a simple loop or list comprehension after you have a set of results. You might also consider not using `get_all_properties()`, and being more explicit, doing something like:

```
records = c.get_rows()
results = []
for record in records:
    results.append({
        "person": record.person[0].full_name,
        "year": record.timestamp.start.year,
        "id": record.id,
    })
```
