### ISSUE TITLE
Can't get date from collection property.

### ISSUE THREAD

**Issue by BlakeStevenson** [jamalex/notion-py#71]
I am having a problem where whenever I try to access the `date` property of a collection entry, I get an object called `NotionDate`: `<notion.collection.NotionDate object at 0x7f20c217de48>`. I am wondering how to get the start and end dates from this object, as these are necessary for the automation I am currently working on.

Thanks!

**Comment by BlakeStevenson** [comment]
Solved, the date was accessible using `row.date.start`.

**Comment by chrishumphries** [comment]
How does this work if the date field as another name besides date?

**Comment by chrishumphries** [comment]
`"{}".format(datetime(row.date.start)` - would this be the right way to format a date property?
