### ISSUE TITLE
How did you sniff the Notion API ? 

### ISSUE THREAD

**Issue by callixte-girard** [jamalex/notion-py#72]
How did you sniff the Notion API ? 
Do they have a REST API ? 
Or do they have a very secured API they gave you the keys for ?

**Comment by Cobertos** [comment]
You can use the Notion.so web view and open the network tab in any web developer toolset. Here's an example where I'm looking for the details of the file upload API.

![image](https://user-images.githubusercontent.com/6759176/69910863-69643b80-13e0-11ea-8516-c3d31e7d0a80.png)

You can see a ton of different endpoints by refreshing the page, filtering only to `XHR` requests, performing the action you are looking to check, and then noting where they hit and what data they send in the network tab.

**Comment by callixte-girard** [comment]
Oh yeah, I already tried that, but I wasn't seeing the column you mention. 
Thank you for the help, I hope I'll find out the methods I'm interested in thanks to this method!

I was wondering, is there any app that can hide these method calls in any way ? So that guys like us can't reverse-engineer their API ?

**Comment by Cobertos** [comment]
No problem

No, there's no way to hide this sort of thing. You can obfuscate it and
structure your API to make it harder to edit things, but at the end of the
day anything you put on the client's computer can be reverse
engineered/taken apart and simulated back to your API.

The complexity involved in trying to build such an obfuscated API also
usually involved a lot more confusion and communication on the business
side so no one really does it.

**Comment by callixte-girard** [comment]
Thank you for your answers. I think they perfectly make sense. Now I know how to display the different requests used by the API.
After filtering on XHR and locating only the exact request I need with the time graph, and I found the request made to add a block : `submitTransaction`. 
But the content of the request, which is in `cookie` if I understood well, seems not significant at all to me ; how did you decrypt it ?

<img width="1440" alt="Screenshot 2019-12-07 at 23 09 54" src="https://user-images.githubusercontent.com/45435811/70381242-3de4d200-1947-11ea-8fb5-fa683e5e2315.png">

Let me clarify.
If you look at my screenshot, these are attributes in the headers section of the `submitTransaction` request :
- _cfduid
- logglytrackingsession
- intercom-session-gpfdrxfd
- amplitude_id_af
But I don't understand :
- what purpose do they serve ?
- where is the part that says "insert a new empty block at this place" 

Hope I'm clear enough, and thank you in advance for your patience !

**Comment by Cobertos** [comment]
Cookie is the browser cookie for the domain you're requesting to. It's sent
to the server for specific requests as an HTTP Header. It's the same as the
data in `document.cookie`. But this isn't the data that's sent in the
request.

For POST, PUT, and other requests, the data is sent in the body of the
message. That's usually at the very bottom of the Headers panel. It maybe
be behind a little '>' accordion menu arrow, as Chrome will automatically
parse JSON sent to the server and display it as a nice object for you to
browse. The data you're looking for should not be in the Headers section.

**Comment by callixte-girard** [comment]
Okay, so I supposed this is what you're talking about (Request Payload), indeed at the very bottom of the Headers section.

<img width="1440" alt="Screenshot 2019-12-08 at 00 23 58" src="https://user-images.githubusercontent.com/45435811/70381812-6671c980-1951-11ea-9466-baf72d0ba7b7.png">

So I just have to generate a random `requestId` and `transactionId`, then generate an id for the new block and set its attributes like in the screenshot, alright ?

How should I turn this JSON into a URL-based HTTP request ? I know how to parse an HTTP response in the form of a JSON but not the opposite.
When you search something on a website, it does something like : https://www.thewebsite.com/?search=your-search
Is it something similar I'm supposed to do ? How can I fit such a large request in just a single URL ?

**Comment by Cobertos** [comment]
GET requests normally pass their parameters as "query string" parameters,
the ones after the ? delimited by & and using = for key value relationship.
To pass the JSON object like this you cant use a URL, you have to use a
request with a body (like POST or PUT) though the server might be expecting
a specific kind.

Also, requestID and transaction ID are not random but are guids. They also
might not be random guids but they might come from some previously called
endpoint to say open a transaction. Notion-py does do all this sort of
Notion handshaking behind the scenes so if you study the code you should
figure out how to do it (I haven't looked deep enough in that part of the
library to know the answer though).

**Comment by callixte-girard** [comment]
Okay I think I understand. Thank you again for your time !
I just have to dig into all of this now... ;-)
