### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ftomassetti** [jamalex/notion-py#80]
I can see tens of issues without answers and PRs which have been waiting for months, so I was wondering if someone is maintaining this project

**Comment by jamalex** [comment]
It's being "maintained" (very slowly) by me. :) My day (and night?) job is running [a nonprofit](https://learningequality.org/), which keeps me pretty busy, so I generally only have time to devote to this during holidays -- such as today!

I'll be working through the PR's first, then triaging issues (some are for feature requests that I'd welcome community contributions on, while others are more critical bugfixes, some of which will likely already have been addressed by the PRs).
