### ISSUE TITLE
Notion Client error

### ISSUE THREAD

**Issue by 8bitgentleman** [jamalex/notion-py#9]
When running notion for the first time it throws several errors and is unable to connect to notion.so

`requests.exceptions.SSLError: HTTPSConnectionPool(host='msgstore.www.notion.so', port=443): Max retries exceeded with url: /primus/?sessionId=aa6704e9-e9e7-45bc-a5bb-e59121633ca8&EIO=3&transport=polling (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)'),))
`

I'm using the Quickstart tutorial in the Readme so I'm not sure what's going on here

**Comment by jamalex** [comment]
I'm not able to replicate this. Are you still seeing it with the latest version of notion-py? My guess is it may have been a network or SSL certificate/CA issue. If you're still seeing it, could you provide your OS, Python version, and any other pertinent details? Thanks!

**Comment by 8bitgentleman** [comment]
Looks like the latest update fixed the issue. Thanks for the help!
