### ISSUE TITLE
Unexpected behaviour with adding rows to a collection

### ISSUE THREAD

**Issue by kevinjalbert** [jamalex/notion-py#92]
With the recent changes in https://github.com/jamalex/notion-py/pull/85, my usage of adding rows to a collection from 0.0.21 to 0.0.25 broke.

For context, I add tasks via the following: https://github.com/kevinjalbert/notion-toolbox/blob/master/alfred/src/add_task.py#L12-L23

What I end up getting is the following:

```
Traceback (most recent call last):
  File "src/add_task.py", line 28, in <module>
    row = collection.add_row()
  File "/usr/local/lib/python3.7/site-packages/notion/collection.py", line 156, in add_row
    view.set("page_sort", view.get("page_sort", []) + [row_id])
AttributeError: 'NoneType' object has no attribute 'set'
```

So for some reason, the `view` is `None` at this point.

-----

Now for the strange part. If I do the following:

```python
    collection = notion_api.tasks_database().collection

    # HACK: For some reason, we need all the views loaded up for the collection.add_row() to work
    #       it also has to be 'printed' for whatever reason, just accessing it doesn't work
    print(collection.parent.views)
...
```

It works 🤔.

I went and looked at the new changes added (https://github.com/jamalex/notion-py/blob/master/notion/collection.py#L152-L156) to see what is happening. I found that the first view for my collection's parent is `None` (which explains the exception). I went and added the following to `collection.py`:

```diff
            # make sure the new record is inserted at the end of each view
            for view in self.parent.views:
+               print(view)
+               if view is None or isinstance(view, CalendarView):
                    continue
                view.set("page_sort", view.get("page_sort", []) + [row_id])
```

It works as expected, and I saw the following output:

```
None
None
None
None
None
None
None
id='afc7fdaa-7870-48e2-9a6c-4b1c98acf05a'
```

So only the last view had a value. I'm not sure _why_ this is the case. Is there maybe some lazy loading going on for views? For additional context, I had monkey-patched out the caching a while back (https://github.com/kevinjalbert/notion-toolbox/commit/8e4e4098ea99eaa5cf24320da5805d0a341b3153) but removed that with this release.

-----

I can live with a temporary solution for my own needs. Although, I'm curious about what is happening here.

**Comment by kevsestrella** [comment]
Hello,

I currently have an issue where collection has no parent. Commenting the hack out fixed the issue.

`File "/Users/kevsestrella/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/alfred/src/add_task.py", line 17, in <module>
    print(collection.parent.views)
AttributeError: 'Collection' object has no attribute 'parent'`

**Comment by jamalex** [comment]
>So only the last view had a value. I'm not sure why this is the case.

Interesting. One guess is that perhaps there were previously some other views, and they got deleted, but their IDs were left on the CollectionViewBlock's `view_ids` field. So when it builds the list of views, it tries to fetch those views and doesn't find them, and hence returns `None`. That may not be accurate, but it was the first thing that came to mind.

I'll incorporate your patch, and also look at making it so that lists of children won't include `None` entries.

**Comment by jamalex** [comment]
@kevinjalbert Would you be able to see whether this addresses it for you?
https://github.com/jamalex/notion-py/pull/96

Thanks!

**Comment by kevinjalbert** [comment]
Tested, and left a comment on the PR: https://github.com/jamalex/notion-py/pull/96#discussion_r365629145.

Mostly works, but I feel there is something else up.

**Comment by kevinjalbert** [comment]
Just as a heads up. I've made my own fork and applied this PR and a quick patch that gets my usage of `notion-py` back to normal.

https://github.com/kevinjalbert/notion-toolbox/commit/13ba5c3bfe0955ef3102eaa99e1d2fc1bdee18bd

I would still really love to see everything resolved in the proper repository. Willing to help out as needed.

**Comment by dukebarman** [comment]
What about merging? Have a same problem

**Comment by zxtheo** [comment]
I second merging this as I too have the same problem @jamalex

**Comment by jvieirar** [comment]
I get 'NoneType' object has no attribute 'id' by just following the example
```
collection = client.get_collection('xxxx') # get an existing collection
cvb = page.children.add_new(CollectionViewBlock, collection=collection)
view = cvb.views.add_new(view_type="table")
```
I think is the same issue

**Comment by distkeys** [comment]
Hitting the same issue in the first time trying adding row through python API

**Comment by jessecdob** [comment]
Hello, 
I am getting the 'NoneType Object' error in version 0.0.28.1 of notion-py.
```
Traceback (most recent call last):
  File "notion_fin.py", line 19, in <module>
    row = cv.collection.add_row()
AttributeError: 'NoneType' object has no attribute 'add_row'
```
